### ISSUE TITLE
Out of memory error with large file profiling

### ISSUE THREAD

**Issue by kPsarakis** [OpertusMundi/BigDataVoyant#3]
The following line fails for large datasets due to memory constraints.
https://github.com/OpertusMundi/BigDataVoyant/blob/ac9b158d92c064cbfa287019c2e78fdf880b8ffb/bigdatavoyant/profiler.py#L150

The stack trace while running the profiler with a 220MB file is the following:

> profile_1  | 2021-01-30 21:38:36,399 - geoprofile.app - ERROR - Exception on /profile/file/vector [POST]
profile_1  | Traceback (most recent call last):
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
profile_1  |     response = self.full_dispatch_request()
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
profile_1  |     rv = self.handle_user_exception(e)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
profile_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
profile_1  |     reraise(exc_type, exc_value, tb)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
profile_1  |     raise value
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
profile_1  |     rv = self.dispatch_request()
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
profile_1  |     return self.view_functions[rule.endpoint](**req.view_args)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/geoprofile-0.1.0-py3.8.egg/geoprofile/app.py", line 579, in profile_file_vector
profile_1  |     report = get_resized_report(ds, form, 'vector')
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/geoprofile-0.1.0-py3.8.egg/geoprofile/utils.py", line 108, in get_resized_report
profile_1  |     report = gdf.profiler.report(basemap_provider=form.basemap_provider.data, basemap_name=form.basemap_name.data,
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/bigdatavoyant/profiler.py", line 414, in report
profile_1  |     'distribution': self.distribution().to_dict(),
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/bigdatavoyant/profiler.py", line 168, in distribution
profile_1  |     attributes = self.categorical() if attributes is None else attributes
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/bigdatavoyant/profiler.py", line 150, in categorical
profile_1  |     nunique = df[col].nunique()
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/vaex/expression.py", line 678, in nunique
profile_1  |     return len(self.unique(dropna=dropna, dropnan=dropnan, dropmissing=dropmissing, selection=selection, delay=delay))
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/vaex/expression.py", line 669, in unique
profile_1  |     return self.ds.unique(self.expression, dropna=dropna, dropnan=dropnan, dropmissing=dropmissing, selection=selection, delay=delay)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/vaex/dataframe.py", line 487, in unique
profile_1  |     keys = np.asarray(keys)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/numpy/core/_asarray.py", line 85, in asarray
profile_1  |     return array(a, dtype, copy=False, order=order)
profile_1  | MemoryError: Unable to allocate 948. GiB for an array with shape (99990,) and data type <U2545264

**Comment by kPsarakis** [comment]
Not relevant anymore after the latest update
